FROM ghcr.io/ublue-os/fedora-toolbox:latest

RUN set -ex && \
    deps='just neofetch redhat-lsb-core poetry black python3-isort python3-devel gtk3 gtk4 cairo-devel gobject-introspection-devel cairo-gobject-devel libadwaita-devel vte291-gtk4-devel' && \
    dnf update && \
    dnf upgrade && \
    dnf install -y $deps && \
    dnf autoremove

CMD ["/usr/bin/neofetch"]
