on:
  release:
    type:
      - published
  push:
    branches:
      - add-rpm-build

name: Create RPM Release

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  build:
    name: Create RPM Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: ls -lah
      - name: build RPM package
        id: rpm_build
        uses: ublue-os/rpmbuild@master
        with:
          spec_file: "pkg/rpm.spec"

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["${{ steps.rpm_build.outputs.source_rpm_path }}"]'
