on:
  release:
    type:
      - published
  push:
    branches:
      - add-rpm-build

name: Create RPM Release

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  build:
    name: Create RPM Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - run: |
          poetry build
      - run: |
          ls -lah
          ls -lah dist
      - name: build RPM package
        id: rpm_build
        uses: ublue-os/rpmbuild@master
        with:
          spec_file: "pkg/rpm.spec"
      - run: ls -lah /home/runner/work/yafti/yafti /home/runner/work/yafti/yafti/rpmbuild rpmbuild/SRPMS
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["${{ steps.rpm_build.outputs.source_rpm_path }}"]'
