name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: System Deps
        run: |
          sudo apt update
          sudo apt install libgirepository1.0-dev libgtk-3-dev libadwaita-1-dev
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - name: Install Project
        run: poetry install --no-interaction
      - name: Check code formatting
        run: poetry run black --check yafti
      - name: Lint code
        run: poetry run ruff yafti
      - name: Run pytest
        run: poetry run pytest --cov=yafti --cov-report=term-missing
